# Generated by Django 4.0.2 on 2022-02-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lanches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=150)),
                ('data_pedido', models.CharField(max_length=150)),
                ('horario', models.CharField(max_length=150)),
                ('qtd', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status_pgto', models.CharField(max_length=150)),
                ('tipo_pgto', models.CharField(max_length=150)),
                ('data_pgto', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='users_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
            ],
        ),
    ]
